name: Build

on:
    push:
        branches: [ main ]
        tags: release-**

jobs:
    build:
        runs-on: [self-hosted, linux, x64, k8s]

        steps:
            - uses: actions/checkout@v3
           
            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                go-version: '1.20.5'
            - name: Display Go version
              run: go version
            - name: Build
              id: build_release
              run: go build -v ./cmd/relay-monitor/"
            - name: Create Release
              if: success()
              id: create_release
              uses: actions/create-release@v1.1.4
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                tag_name: ${{ github.ref }}
                release_name: ${{ github.ref }}
                body: Release ${{ github.ref }}
                draft: false